# Generated by Django 2.0 on 2020-03-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_potentialcontact_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcontact',
            name='patient_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timeline_of_Patient', to='app.PatientTimeline'),
        ),
        migrations.AlterField(
            model_name='potentialcontact',
            name='public_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Timeline_of_Public', to='app.PublicTimeline'),
        ),
    ]
