# Generated by Django 2.0 on 2020-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200320_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialcontact',
            name='activities',
            field=models.ManyToManyField(to='app.Activity'),
        ),
    ]
